name: CI

# on: [push, pull_request]
on: [repository_dispatch, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.14'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install hypothesis==6.151.0 pure_eval==0.2.3 pydantic_core==2.41.5 torch==2.10.0+cpu uv==0.9.26
      - run: |
          python -m pip install --upgrade pip
      - run: |
          python -m pip install -r requirements.txt
      - run: |
          python -m pip install numpy
          pip -v install -e .
          python3 -m pip install pytest pytest-asyncio hypothesis
      - run: |
          python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu
          python3 -m pip install .
      - run: |
          python3 -m pytest
    env:
      LC_ALL: POSIX